databases:
  - name: podcatcher-db
    region: frankfurt
    databaseName: podcatcher
    user: podcatcher
    plan: free

services:
  - type: web
    name: podcatcher-web
    region: frankfurt
    runtime: ruby
    plan: starter
    buildCommand: "bundle install && bin/rails assets:precompile && bin/rails assets:clean && bin/rails db:prepare"
    startCommand: "bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: podcatcher-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: CDN_HOST
        value: https://dwh44x2ky3mrl.cloudfront.net
  - type: worker
    name: podcatcher-worker
    region: frankfurt
    runtime: ruby
    plan: starter
    buildCommand: "bundle install && bin/rails db:prepare"
    startCommand: "bin/jobs"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: podcatcher-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CDN_HOST
        value: https://dwh44x2ky3mrl.cloudfront.net
